### PR TITLE
add missing wowgd methods and tests

### PR DESCRIPTION
**Pull request by NovikovRoman**
except methods:
- WoWSpellSearch
- WoWMediaSearch

wowgd - profession.go

`
CraftedQuantity struct {
    Minimum int `json:"minimum"`
    Maximum int `json:"maximum"`
} `json:"crafted_quantity"`
`
Returns 1.0

wrote float32. Maybe you need float64?

### CODE REVIEW

**Comment by FuzzyStatic** [comment]
What is the value in the JSON data?

**Comment by NovikovRoman** [comment]
> What is the value in the JSON data?

float

**Comment by FuzzyStatic** [comment]
I mean the actually value in the body before being unmarshalled into the structure?

**Comment by NovikovRoman** [comment]
API returns value in JSON data as 1.0 (minimum & maximum).

**Comment by FuzzyStatic** [comment]
I don't know how high the values can go. I don't think it matters for most people if it's float32 or float64, so if you want to be on the safe side you can make it a float64.

**Comment by NovikovRoman** [comment]
You are the master here :). Decide for yourself.

**Pull request merged**
