### PR TITLE
Expanded LegacyProfileLadders struct

### PR DESCRIPTION
**Pull request by FuzzyStatic**

### CODE REVIEW

**Comment by FuzzyStatic** [comment]
Hey @ccod,

I would like to maintain proper support of the structures for this package. Thank you for completing the LegacyProfileLadders data. Can you update the _test.go file with a profileID that will populate these fields?

Thanks,
FuzzyStatic

**Comment by ccod** [comment]
I can do that, but I am not too happy with it... the endpoint was rather unwieldy to use. 

```go
var l interface{}

for i := 0; i < len(ladders.CurrentSeason); i++ {
    fmt.Printf("ladder summary: %v\n", ladders.CurrentSeason[i])
    if ladders.CurrentSeason[i].Ladder[0] && ladders.CurrentSeason[i].Ladder[0].MatchMakingQueue == "LOTV_SOLO" {
        fmt.Println("found it")
        l = ladders.CurrentSeason[i]
        break
    }
}
```

I know `interface{}` isn't right, 
but it isn't quite `var l sc2c.LegacyProfileLadders.CurrentSeason.Ladder` either.
How do you name a type that is nested in multiple []structs?
What is the convention for making sure you don't index into something that doesn't exist?

I decided to solve my particular use case with different endpoints because I was unhappy with this.

Thoughts?

**Comment by FuzzyStatic** [comment]
Can you share an example output (or update the test file) with what it looks like? 

Unfortunately, we are stuck with whatever output is given to us by Blizzard, but if I have a better understanding of what is being returned I can create a better abstracted function.

**Comment by FuzzyStatic** [comment]
What piece of data are you looking for specifically? All Solo MMQ? All Ranked Solo MMQ?

**Pull request merged**
