### PR TITLE
Expand Achievement JSON to include sub Criteria

### PR DESCRIPTION
**Pull request by Fryyyyy**
e.g ID = 12989

Generated by json-to-go with one manual edit ({}interface -> string on description field)

### CODE REVIEW

**Comment by Fryyyyy** [comment]
I guess theoretically Achievements can be more deeply nested than this, could make it more generic with a `[]struct`

**Comment by FuzzyStatic** [comment]
What if you next it within itself:

```
type ChildCriteria []struct {
	ID          int    `json:"id"`
	Description string `json:"description"`
	Amount      int    `json:"amount"`
	Faction     struct {
		Type string `json:"type,omitempty"`
		Name string `json:"name,omitempty"`
	} `json:"faction,omitempty"`
	Achievement struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		ID   int    `json:"id"`
	} `json:"achievement,omitempty"`
	Operator struct {
		Type string `json:"type"`
		Name string `json:"name"`
	} `json:"operator,omitempty"`
	ChildCriteria ChildCriteria `json:"child_criteria,omitempty"`
}

// Achievement structure
type Achievement struct {
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
	ID       int `json:"id"`
	Category struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		Name string `json:"name"`
		ID   int    `json:"id"`
	} `json:"category"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Points        int    `json:"points"`
	IsAccountWide bool   `json:"is_account_wide"`
	Criteria      struct {
		ID          int         `json:"id"`
		Description interface{} `json:"description"`
		Amount      int         `json:"amount"`
		Operator    struct {
			Type string `json:"type"`
			Name string `json:"name"`
		} `json:"operator"`
		ChildCriteria ChildCriteria `json:"child_criteria,omitempty"`
	} `json:"criteria"`
	RewardDescription string `json:"reward_description"`
	Media             struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		ID int `json:"id"`
	} `json:"media"`
	DisplayOrder int `json:"display_order"`
}
```

**Comment by Fryyyyy** [comment]
Yup that's what I was hinting at with my comment about `could make it more generic with a []struct`
I'll update the PR shortly

**Comment by FuzzyStatic** [comment]
You are missing Faction

```go
Faction struct {	
   Type string `json:"type"`	
   Name string `json:"name"`	
} `json:"faction"`
```

**Comment by Fryyyyy** [comment]
Hm I wonder if the initial Criteria block can contain Faction as well as the Child ones?
I'm guessing yes and will put it as optional

**Pull request merged**
