### PR TITLE
Add SC2 ladder game data API

### PR DESCRIPTION
**Pull request by w1ck3dg0ph3r**
Closes issue #21

### CODE REVIEW

**Comment by FuzzyStatic** [comment]
This seems to work for the EU region but not the US, can you specify what regions it works for in the comment?

**Comment by w1ck3dg0ph3r** [comment]
Just tested on US, KR and CN - API works fine. I think the problem is I put EU ladder ID in the test, should I change it to some US one?

**Comment by FuzzyStatic** [comment]
Please. Afterward, I'll merge your PR.

**Comment by FuzzyStatic** [comment]
TY for your PR!

**Pull request merged**
