### PR TITLE
fix getStructData wowp.CharacterProfileSummary

### PR DESCRIPTION
**Pull request by NovikovRoman**
Invalid BattlenetSchemaRevision check condition.

Test:
region - eu
character - news
realm - blackhand

### CODE REVIEW

**Comment by FuzzyStatic** [comment]
@NovikovRoman the logic seems backward here. Before if the revision was less than 24 it would require a different structure, now if it is greater than 23 it uses the old structure?

**Comment by NovikovRoman** [comment]
> @NovikovRoman the logic seems backward here. Before if the revision was less than 24 it would require a different structure, now if it is greater than 23 it uses the old structure?

apparently so :(

**Comment by FuzzyStatic** [comment]
@NovikovRoman I will have to properly visit this and see what is going on.

**Comment by NovikovRoman** [comment]
> @NovikovRoman I will have to properly visit this and see what is going on.
[news-blackhand.json.txt](https://github.com/FuzzyStatic/blizzard/files/7009214/news-blackhand.json.txt)

**Comment by FuzzyStatic** [comment]
@NovikovRoman can I get the headers as well.

**Comment by NovikovRoman** [comment]
> can I get the headers as well.
[headers.log](https://github.com/FuzzyStatic/blizzard/files/7011922/headers.log)

**Comment by NovikovRoman** [comment]
Does anyone have an example of Battlenet-Schema-Revision < 22? Where is active_title as a string.

**Pull request closed without merging**
