### PR TITLE
Add MediaSearch query to WoW Client

### PR DESCRIPTION
**Pull request by AlexMeuer**
The type was defined by the api call was missing.

### CODE REVIEW

**Comment by FuzzyStatic** [comment]
@AlexMeuer when you run this call do you get data back?

**Comment by AlexMeuer** [comment]
Now getting back the expected MediaSearch struct response. I hadn't committed the format string when I initially created the PR.

**Comment by FuzzyStatic** [comment]
Can you include the output from the test?

**Comment by AlexMeuer** [comment]
Ah 🤦 I was being stupid.
Not pasting test output because it's quite long, but it's working in latest commit. I've been using `go test -run TestWoWMediaSearch` to verify it.

**Comment by FuzzyStatic** [comment]
@AlexMeuer can you multiline the getStructData the same way other functions do it? Shredder that I'll merge it.

**Comment by AlexMeuer** [comment]
Sure, will do. It'll be a little later in the weekend before I get round to it though.

**Pull request merged**
