### PR TITLE
Add Item Search API

### PR DESCRIPTION
**Pull request by msadowskigraduate**
Added implementation for WoW Item Search functionality.

### CODE REVIEW

**Comment by FuzzyStatic** [comment]
@msadowskigraduate can you include the unit test output for this function?

**Comment by msadowskigraduate** [comment]
> @msadowskigraduate can you include the unit test output for this function?
Yeah sure, would you like me to post it here or add as a comment to the code? Adding assertion on the test case is a bit dodgy, as the data might change with new expansion being released making the test output quite volatile

**Comment by msadowskigraduate** [comment]
`❯ /usr/local/bin/go test -timeout 30s -run ^TestWoWItemSearch$ github.com/FuzzyStatic/blizzard/v3 -count=1 -v
=== RUN   TestWoWItemSearch
    wowgd_test.go:436: &{Page:1 PageSize:5 MaxPageSize:5 PageCount:200 ResultCountCapped:true Results:[{Key:{Href:https://us.api.blizzard.com/data/wow/item/176811?namespace=static-9.2.7_44981-us} Data:{Level:120 RequiredLevel:51 SellPrice:2500 ItemSubclass:{Name:{RuRU:Зелья EnGB:Potion ZhTW:藥水 KoKR:물약 EnUS:Potion EsMX:Poción PtBR:Poção EsES:Poción ZhCN:药水 FrFR:Potion DeDE:Tränke} ID:1} IsEquippable:false PurchaseQuantity:1 Media:{ID:176811} ItemClass:{Name:{RuRU:Расходуемые EnGB:Consumable ZhTW:消耗品 KoKR:소비용품 EnUS:Consumable EsMX:Consumible PtBR:Consumível EsES:Consumible ZhCN:消耗品 FrFR:Consommable DeDE:Verbrauchbares} ID:0} Name:{RuRU:Зелье жертвенной анимы EnGB:Potion of Sacrificial Anima ZhTW:靈魄獻祭藥水 KoKR:희생 령의 물약 EnUS:Potion of Sacrificial Anima EsMX:Poción de ánima sacrificial PtBR:Poção de Ânima Sacrifical EsES:Poción de sacrificio de ánima ZhCN:献祭心能药水 FrFR:Potion d’anima sacrificiel DeDE:Trank des Animaopfers} Quality:{Type:COMMON Name:{RuRU:Обычное EnGB:Common ZhTW:普通 KoKR:일반 EnUS:Common EsMX:Común PtBR:Comum EsES:Común ZhCN:普通 FrFR:Commun DeDE:Gewöhnlich}} InventoryType:{Type:NON_EQUIP Name:{RuRU:Неэкипируемое EnGB:Non-equippable ZhTW:無法裝備 KoKR:착용 불가 EnUS:Non-equippable EsMX:No equipable PtBR:Não equipável EsES:No se puede equipar ZhCN:无法装备 FrFR:Objet hors équipement DeDE:Nicht anlegbar}} PurchasePrice:10000 MaxCount:0 IsStackable:true ID:176811}} {Key:{Href:https://us.api.blizzard.com/data/wow/item/178015?namespace=static-9.2.7_44981-us} Data:{Level:120 RequiredLevel:50 SellPrice:250000 ItemSubclass:{Name:{RuRU:Другое EnGB:Other ZhTW:其他 KoKR:기타 EnUS:Other EsMX:Otros PtBR:Outro EsES:Otros ZhCN:其它 FrFR:Autres DeDE:Sonstiges} ID:8} IsEquippable:false PurchaseQuantity:1 Media:{ID:178015} ItemClass:{Name:{RuRU:Расходуемые EnGB:Consumable ZhTW:消耗品 KoKR:소비용품 EnUS:Consumable EsMX:Consumible PtBR:Consumível EsES:Consumible ZhCN:消耗品 FrFR:Consommable DeDE:Verbrauchbares} ID:0} Name:{RuRU:Потерявшая силу отрава EnGB:Spoiled Contaminant ZhTW:損壞的污染樣本 KoKR:손상된 오염원 EnUS:Spoiled Contaminant EsMX:Contaminante arruinado PtBR:Contaminante Estragado EsES:Contaminante estropeado ZhCN:变质的污染物 FrFR:Contaminant dénaturé DeDE:Verdorbene Verunreinigung} Quality:{Type:POOR Name:{RuRU:Низкое EnGB:Poor ZhTW:粗糙 KoKR:하급 EnUS:Poor EsMX:Pobre PtBR:Inferior EsES:Pobre ZhCN:粗糙 FrFR:Mauvais DeDE:Schlecht}} InventoryType:{Type:NON_EQUIP Name:{RuRU:Неэкипируемое EnGB:Non-equippable ZhTW:無法裝備 KoKR:착용 불가 EnUS:Non-equippable EsMX:No equipable PtBR:Não equipável EsES:No se puede equipar ZhCN:无法装备 FrFR:Objet hors équipement DeDE:Nicht anlegbar}} PurchasePrice:250001 MaxCount:0 IsStackable:true ID:178015}} {Key:{Href:https://us.api.blizzard.com/data/wow/item/171271?namespace=static-9.2.7_44981-us} Data:{Level:120 RequiredLevel:51 SellPrice:2500 ItemSubclass:{Name:{RuRU:Зелья EnGB:Potion ZhTW:藥水 KoKR:물약 EnUS:Potion EsMX:Poción PtBR:Poção EsES:Poción ZhCN:药水 FrFR:Potion DeDE:Tränke} ID:1} IsEquippable:false PurchaseQuantity:1 Media:{ID:171271} ItemClass:{Name:{RuRU:Расходуемые EnGB:Consumable ZhTW:消耗品 KoKR:소비용품 EnUS:Consumable EsMX:Consumible PtBR:Consumível EsES:Consumible ZhCN:消耗品 FrFR:Consommable DeDE:Verbrauchbares} ID:0} Name:{RuRU:Зелье закаленных теней EnGB:Potion of Hardened Shadows ZhTW:堅實暗影藥水 KoKR:경화된 어둠의 물약 EnUS:Potion of Hardened Shadows EsMX:Poción de sombras endurecidas PtBR:Poção das Sombras Endurecidas EsES:Poción de sombras endurecidas ZhCN:硬化暗影药水 FrFR:Potion d’ombres endurcies DeDE:Trank der verhärteten Schatten} Quality:{Type:COMMON Name:{RuRU:Обычное EnGB:Common ZhTW:普通 KoKR:일반 EnUS:Common EsMX:Común PtBR:Comum EsES:Común ZhCN:普通 FrFR:Commun DeDE:Gewöhnlich}} InventoryType:{Type:NON_EQUIP Name:{RuRU:Неэкипируемое EnGB:Non-equippable ZhTW:無法裝備 KoKR:착용 불가 EnUS:Non-equippable EsMX:No equipable PtBR:Não equipável EsES:No se puede equipar ZhCN:无法装备 FrFR:Objet hors équipement DeDE:Nicht anlegbar}} PurchasePrice:10000 MaxCount:0 IsStackable:true ID:171271}} {Key:{Href:https://us.api.blizzard.com/data/wow/item/171281?namespace=static-9.2.7_44981-us} Data:{Level:120 RequiredLevel:51 SellPrice:6250 ItemSubclass:{Name:{RuRU:Другое EnGB:Other ZhTW:其他 KoKR:기타 EnUS:Other EsMX:Otros PtBR:Outro EsES:Otros ZhCN:其它 FrFR:Autres DeDE:Sonstiges} ID:8} IsEquippable:false PurchaseQuantity:1 Media:{ID:171281} ItemClass:{Name:{RuRU:Расходуемые EnGB:Consumable ZhTW:消耗品 KoKR:소비용품 EnUS:Consumable EsMX:Consumible PtBR:Consumível EsES:Consumible ZhCN:消耗品 FrFR:Consommable DeDE:Verbrauchbares} ID:0} Name:{RuRU:Извечный котел EnGB:Eternal Cauldron ZhTW:永恆大鍋 KoKR:영원의 가마솥 EnUS:Eternal Cauldron EsMX:Caldero eterno PtBR:Caldeirão Eterno EsES:Caldera eterna ZhCN:永恒药锅 FrFR:Chaudron éternel DeDE:Ewiger Kessel} Quality:{Type:COMMON Name:{RuRU:Обычное EnGB:Common ZhTW:普通 KoKR:일반 EnUS:Common EsMX:Común PtBR:Comum EsES:Común ZhCN:普通 FrFR:Commun DeDE:Gewöhnlich}} InventoryType:{Type:NON_EQUIP Name:{RuRU:Неэкипируемое EnGB:Non-equippable ZhTW:無法裝備 KoKR:착용 불가 EnUS:Non-equippable EsMX:No equipable PtBR:Não equipável EsES:No se puede equipar ZhCN:无法装备 FrFR:Objet hors équipement DeDE:Nicht anlegbar}} PurchasePrice:25000 MaxCount:0 IsStackable:true ID:171281}} {Key:{Href:https://us.api.blizzard.com/data/wow/item/171349?namespace=static-9.2.7_44981-us} Data:{Level:120 RequiredLevel:51 SellPrice:2500 ItemSubclass:{Name:{RuRU:Зелья EnGB:Potion ZhTW:藥水 KoKR:물약 EnUS:Potion EsMX:Poción PtBR:Poção EsES:Poción ZhCN:药水 FrFR:Potion DeDE:Tränke} ID:1} IsEquippable:false PurchaseQuantity:1 Media:{ID:171349} ItemClass:{Name:{RuRU:Расходуемые EnGB:Consumable ZhTW:消耗品 KoKR:소비용품 EnUS:Consumable EsMX:Consumible PtBR:Consumível EsES:Consumible ZhCN:消耗品 FrFR:Consommable DeDE:Verbrauchbares} ID:0} Name:{RuRU:Зелье фантомного огня EnGB:Potion of Phantom Fire ZhTW:魅影之火藥水 KoKR:도깨비불의 물약 EnUS:Potion of Phantom Fire EsMX:Poción de fuego fantasma PtBR:Poção do Fogo Fantasma EsES:Poción de fuego fantasmal ZhCN:幻影火焰药水 FrFR:Potion de feu fantomatique DeDE:Trank des Phantomfeuers} Quality:{Type:COMMON Name:{RuRU:Обычное EnGB:Common ZhTW:普通 KoKR:일반 EnUS:Common EsMX:Común PtBR:Comum EsES:Común ZhCN:普通 FrFR:Commun DeDE:Gewöhnlich}} InventoryType:{Type:NON_EQUIP Name:{RuRU:Неэкипируемое EnGB:Non-equippable ZhTW:無法裝備 KoKR:착용 불가 EnUS:Non-equippable EsMX:No equipable PtBR:Não equipável EsES:No se puede equipar ZhCN:无法装备 FrFR:Objet hors équipement DeDE:Nicht anlegbar}} PurchasePrice:10000 MaxCount:0 IsStackable:true ID:171349}}]}
--- PASS: TestWoWItemSearch (1.16s)
PASS
ok  	github.com/FuzzyStatic/blizzard/v3	2.504s`

**Comment by FuzzyStatic** [comment]
@msadowskigraduate looks good, thanks for the contribution!

**Pull request merged**
